name: Android_build_and_test

on:
  pull_request:
    branches:
      - "develop"

  push:
    branches:
      - "develop"

jobs:
  build:
    needs: setup-environment
    name: Build project
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle
      run: ./gradlew clean build

  unit-test:
    needs: build
    name: Run unit tests on PR in develop
    runs-on: ubuntu-latest

    steps:
      - name: Run unit tests
        run: ./gradlew test
