name: Android build and test project

on:
  pull_request:
    branches:
      - "develop"
      - "main"
  push:
    branches:
      - "develop"
      - "main"

jobs:
  setup-environment:
    name: Setup environment variables
    runs-on: ubuntu-latest

    env:
      REPO_OWNER: ${{ github.repository_owner }}
      REPO_NAME: ${{ github.event.repository.name }}

    steps:
      - name: Increment repo BUILD_NUMBER variable
        env:
          GH_TOKEN: ${{ secrets.PAT_UPDATE_VARS }}
        run: |
          VAR_NAME="BUILD_NUMBER"
          API="https://api.github.com/repos/$REPO_OWNER/$REPO_NAME/actions/variables/$VAR_NAME/"

          CURRENT=$(curl -s -H "Authorization: Bearer $GH_TOKEN" "$API" | jq -r .value)
          NEXT=$((CURRENT+1))

          curl -s -X PATCH "$API" \
            -H "Authorization: Bearer $GH_TOKEN" \
            -H "Content-Type: application/json" \
            -d "{\"name\":\"$VAR_NAME\",\"value\":\"$NEXT\"}"

          echo "build.number=$NEXT" >> local.properties

      - name: Setup app url
        run: |
          API="https://api.github.com/repos/$REPO_OWNER/$REPO_NAME/"
          echo "app.repos.url=$API" >> local.properties

  build:
    name: Build project
    needs: setup-environment
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: "temurin"
        cache: gradle

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v5

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle
      run: ./gradlew clean build --scan

    - name: Upload build reports
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: build-reports
        path: /build/reports/

  unit-test:
    needs: build
    name: Run unit tests
    runs-on: ubuntu-latest

    steps:
      - name: Run unit tests
        run: ./gradlew clean test
