name: Scan with Detekt

on:
  push:
    branches: [ "develop", "main" ]
  pull_request:
    branches: [ "develop", "main" ]
  schedule:
     - cron: '30 14 * * 0'

jobs:
  scan:
    name: Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: gradle

      - name: Ensure local.properties file
        run: |
          if [ ! -f local.properties ]; then
            touch local.properties
          fi

      - name: Setup detekt
        uses: peter-murray/setup-detekt@v3

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Run Detekt
        continue-on-error: true
        run: detekt --input ${{ github.workspace }} --report sarif:${{ github.workspace }}/detekt.sarif.json

      - name: Create reports directory
        run: mkdir -p build/reports/detekt

      # Modifies the SARIF output produced by Detekt so that absolute URIs are relative
      # This is so we can easily map results onto their source files
      # This can be removed once relative URI support lands in Detekt: https://git.io/JLBbA
      - name: Make artifact location URIs relative
        continue-on-error: true
        run: |
          echo "$(
            jq --arg github_workspace ${{ github.workspace }} \
              '. | ( .runs[].results[].locations[].physicalLocation.artifactLocation.uri |= if test($github_workspace) then .[($github_workspace | length | . + 1):] else . end )' \
              ${{ github.workspace }}/detekt.sarif.json
          )" > ${{ github.workspace }}/detekt.sarif.json

      # Uploads results to GitHub repository using the upload-sarif action
      - name: Upload detekt results to GitHub
        uses: github/codeql-action/upload-sarif@v3
        with:
          # Path to SARIF file relative to the root of the repository
          sarif_file: ${{ github.workspace }}/detekt.sarif.json
          checkout_path: ${{ github.workspace }}

      - name: Upload Detekt report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: detekt-report
          path: build/reports/detekt/
          retention-days: 7