name: Scan with Detekt

on:
  push:
    branches: [ "develop", "main" ]
  pull_request:
    branches: [ "develop", "main" ]
  schedule:
     - cron: '30 14 * * 0'

jobs:
  scan:
    name: Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: gradle

      - name: Ensure local.properties file
        run: |
          if [ ! -f local.properties ]; then
            touch local.properties
          fi

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Run Detekt
        run: ./gradlew detekt

      - name: Create reports directory
        run: mkdir -p build/reports/detekt

      - name: Upload Detekt report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: detekt-report
          path: build/reports/detekt/
          retention-days: 7
